/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AgentsRouteImport } from './routes/agents'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardScheduledRouteImport } from './routes/dashboard/scheduled'
import { Route as DashboardRaiseRouteImport } from './routes/dashboard/raise'
import { Route as DashboardMyNftsRouteImport } from './routes/dashboard/my-nfts'
import { Route as DashboardMyAuctionsRouteImport } from './routes/dashboard/my-auctions'
import { Route as DashboardLiveRouteImport } from './routes/dashboard/live'
import { Route as DashboardBidsRouteImport } from './routes/dashboard/bids'
import { Route as AuctionIdRouteImport } from './routes/auction/$id'

const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRoute = AgentsRouteImport.update({
  id: '/agents',
  path: '/agents',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardScheduledRoute = DashboardScheduledRouteImport.update({
  id: '/scheduled',
  path: '/scheduled',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardRaiseRoute = DashboardRaiseRouteImport.update({
  id: '/raise',
  path: '/raise',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyNftsRoute = DashboardMyNftsRouteImport.update({
  id: '/my-nfts',
  path: '/my-nfts',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMyAuctionsRoute = DashboardMyAuctionsRouteImport.update({
  id: '/my-auctions',
  path: '/my-auctions',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLiveRoute = DashboardLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBidsRoute = DashboardBidsRouteImport.update({
  id: '/bids',
  path: '/bids',
  getParentRoute: () => DashboardRoute,
} as any)
const AuctionIdRoute = AuctionIdRouteImport.update({
  id: '/auction/$id',
  path: '/auction/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auction/$id': typeof AuctionIdRoute
  '/dashboard/bids': typeof DashboardBidsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/my-auctions': typeof DashboardMyAuctionsRoute
  '/dashboard/my-nfts': typeof DashboardMyNftsRoute
  '/dashboard/raise': typeof DashboardRaiseRoute
  '/dashboard/scheduled': typeof DashboardScheduledRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/auction/$id': typeof AuctionIdRoute
  '/dashboard/bids': typeof DashboardBidsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/my-auctions': typeof DashboardMyAuctionsRoute
  '/dashboard/my-nfts': typeof DashboardMyNftsRoute
  '/dashboard/raise': typeof DashboardRaiseRoute
  '/dashboard/scheduled': typeof DashboardScheduledRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents': typeof AgentsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/auction/$id': typeof AuctionIdRoute
  '/dashboard/bids': typeof DashboardBidsRoute
  '/dashboard/live': typeof DashboardLiveRoute
  '/dashboard/my-auctions': typeof DashboardMyAuctionsRoute
  '/dashboard/my-nfts': typeof DashboardMyNftsRoute
  '/dashboard/raise': typeof DashboardRaiseRoute
  '/dashboard/scheduled': typeof DashboardScheduledRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents'
    | '/dashboard'
    | '/auction/$id'
    | '/dashboard/bids'
    | '/dashboard/live'
    | '/dashboard/my-auctions'
    | '/dashboard/my-nfts'
    | '/dashboard/raise'
    | '/dashboard/scheduled'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents'
    | '/auction/$id'
    | '/dashboard/bids'
    | '/dashboard/live'
    | '/dashboard/my-auctions'
    | '/dashboard/my-nfts'
    | '/dashboard/raise'
    | '/dashboard/scheduled'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/agents'
    | '/dashboard'
    | '/auction/$id'
    | '/dashboard/bids'
    | '/dashboard/live'
    | '/dashboard/my-auctions'
    | '/dashboard/my-nfts'
    | '/dashboard/raise'
    | '/dashboard/scheduled'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsRoute: typeof AgentsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  AuctionIdRoute: typeof AuctionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents': {
      id: '/agents'
      path: '/agents'
      fullPath: '/agents'
      preLoaderRoute: typeof AgentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/scheduled': {
      id: '/dashboard/scheduled'
      path: '/scheduled'
      fullPath: '/dashboard/scheduled'
      preLoaderRoute: typeof DashboardScheduledRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/raise': {
      id: '/dashboard/raise'
      path: '/raise'
      fullPath: '/dashboard/raise'
      preLoaderRoute: typeof DashboardRaiseRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-nfts': {
      id: '/dashboard/my-nfts'
      path: '/my-nfts'
      fullPath: '/dashboard/my-nfts'
      preLoaderRoute: typeof DashboardMyNftsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/my-auctions': {
      id: '/dashboard/my-auctions'
      path: '/my-auctions'
      fullPath: '/dashboard/my-auctions'
      preLoaderRoute: typeof DashboardMyAuctionsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/live': {
      id: '/dashboard/live'
      path: '/live'
      fullPath: '/dashboard/live'
      preLoaderRoute: typeof DashboardLiveRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/bids': {
      id: '/dashboard/bids'
      path: '/bids'
      fullPath: '/dashboard/bids'
      preLoaderRoute: typeof DashboardBidsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/auction/$id': {
      id: '/auction/$id'
      path: '/auction/$id'
      fullPath: '/auction/$id'
      preLoaderRoute: typeof AuctionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardBidsRoute: typeof DashboardBidsRoute
  DashboardLiveRoute: typeof DashboardLiveRoute
  DashboardMyAuctionsRoute: typeof DashboardMyAuctionsRoute
  DashboardMyNftsRoute: typeof DashboardMyNftsRoute
  DashboardRaiseRoute: typeof DashboardRaiseRoute
  DashboardScheduledRoute: typeof DashboardScheduledRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBidsRoute: DashboardBidsRoute,
  DashboardLiveRoute: DashboardLiveRoute,
  DashboardMyAuctionsRoute: DashboardMyAuctionsRoute,
  DashboardMyNftsRoute: DashboardMyNftsRoute,
  DashboardRaiseRoute: DashboardRaiseRoute,
  DashboardScheduledRoute: DashboardScheduledRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsRoute: AgentsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  AuctionIdRoute: AuctionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
